package nes

type Instruction struct {
	Mnemonic          string
	AddressingMode    AddressingMode
	InstructionSize   uint8
	InstructionCycles uint8
}

var instructions = [256]Instruction{
	{"BRK", AddressingModeImplied, 1, 7},     // 0x00
	{"ORA", AddressingModeIndirectX, 2, 6},   // 0x01
	{"???", AddressingModeImplied, 0, 0},     // 0x02
	{"???", AddressingModeImplied, 0, 0},     // 0x03
	{"???", AddressingModeImplied, 0, 0},     // 0x04
	{"ORA", AddressingModeZeroPage, 2, 3},    // 0x05
	{"ASL", AddressingModeZeroPage, 2, 5},    // 0x06
	{"???", AddressingModeImplied, 0, 0},     // 0x07
	{"PHP", AddressingModeImplied, 1, 3},     // 0x08
	{"ORA", AddressingModeImmediate, 2, 2},   // 0x09
	{"ASL", AddressingModeAccumulator, 1, 2}, // 0x0A
	{"???", AddressingModeImplied, 0, 0},     // 0x0B
	{"???", AddressingModeImplied, 0, 0},     // 0x0C
	{"ORA", AddressingModeAbsolute, 3, 4},    // 0x0D
	{"ASL", AddressingModeAbsolute, 3, 6},    // 0x0E
	{"???", AddressingModeImplied, 0, 0},     // 0x0F
	{"BPL", AddressingModeRelative, 2, 2},    // 0x10
	{"ORA", AddressingModeIndirectY, 2, 5},   // 0x11
	{"???", AddressingModeImplied, 0, 0},     // 0x12
	{"???", AddressingModeImplied, 0, 0},     // 0x13
	{"???", AddressingModeImplied, 0, 0},     // 0x14
	{"ORA", AddressingModeZeroPageX, 2, 4},   // 0x15
	{"ASL", AddressingModeZeroPageX, 2, 6},   // 0x16
	{"???", AddressingModeImplied, 0, 0},     // 0x17
	{"CLC", AddressingModeImplied, 1, 2},     // 0x18
	{"ORA", AddressingModeAbsoluteY, 3, 4},   // 0x19
	{"???", AddressingModeImplied, 0, 0},     // 0x1A
	{"???", AddressingModeImplied, 0, 0},     // 0x1B
	{"???", AddressingModeImplied, 0, 0},     // 0x1C
	{"ORA", AddressingModeAbsoluteX, 3, 4},   // 0x1D
	{"ASL", AddressingModeAbsoluteX, 3, 7},   // 0x1E
	{"???", AddressingModeImplied, 0, 0},     // 0x1F
	{"JSR", AddressingModeAbsolute, 3, 6},    // 0x20
	{"AND", AddressingModeIndirectX, 2, 6},   // 0x21
	{"???", AddressingModeImplied, 0, 0},     // 0x22
	{"???", AddressingModeImplied, 0, 0},     // 0x23
	{"BIT", AddressingModeZeroPage, 2, 3},    // 0x24
	{"AND", AddressingModeZeroPage, 2, 3},    // 0x25
	{"ROL", AddressingModeZeroPage, 2, 5},    // 0x26
	{"???", AddressingModeImplied, 0, 0},     // 0x27
	{"PLP", AddressingModeImplied, 1, 4},     // 0x28
	{"AND", AddressingModeImmediate, 2, 2},   // 0x29
	{"ROL", AddressingModeAccumulator, 1, 2}, // 0x2A
	{"???", AddressingModeImplied, 0, 0},     // 0x2B
	{"BIT", AddressingModeAbsolute, 3, 4},    // 0x2C
	{"AND", AddressingModeAbsolute, 3, 4},    // 0x2D
	{"ROL", AddressingModeAbsolute, 3, 6},    // 0x2E
	{"???", AddressingModeImplied, 0, 0},     // 0x2F
	{"BMI", AddressingModeRelative, 2, 2},    // 0x30
	{"AND", AddressingModeIndirectY, 2, 5},   // 0x31
	{"???", AddressingModeImplied, 0, 0},     // 0x32
	{"???", AddressingModeImplied, 0, 0},     // 0x33
	{"???", AddressingModeImplied, 0, 0},     // 0x34
	{"AND", AddressingModeZeroPageX, 2, 4},   // 0x35
	{"ROL", AddressingModeZeroPageX, 2, 6},   // 0x36
	{"???", AddressingModeImplied, 0, 0},     // 0x37
	{"SEC", AddressingModeImplied, 1, 2},     // 0x38
	{"AND", AddressingModeAbsoluteY, 3, 4},   // 0x39
	{"???", AddressingModeImplied, 0, 0},     // 0x3A
	{"???", AddressingModeImplied, 0, 0},     // 0x3B
	{"???", AddressingModeImplied, 0, 0},     // 0x3C
	{"AND", AddressingModeAbsoluteX, 3, 4},   // 0x3D
	{"ROL", AddressingModeAbsoluteX, 3, 7},   // 0x3E
	{"???", AddressingModeImplied, 0, 0},     // 0x3F
	{"RTI", AddressingModeImplied, 1, 6},     // 0x40
	{"EOR", AddressingModeIndirectX, 2, 6},   // 0x41
	{"???", AddressingModeImplied, 0, 0},     // 0x42
	{"???", AddressingModeImplied, 0, 0},     // 0x43
	{"???", AddressingModeImplied, 0, 0},     // 0x44
	{"EOR", AddressingModeZeroPage, 2, 3},    // 0x45
	{"LSR", AddressingModeZeroPage, 2, 5},    // 0x46
	{"???", AddressingModeImplied, 0, 0},     // 0x47
	{"PHA", AddressingModeImplied, 1, 3},     // 0x48
	{"EOR", AddressingModeImmediate, 2, 2},   // 0x49
	{"LSR", AddressingModeAccumulator, 1, 2}, // 0x4A
	{"???", AddressingModeImplied, 0, 0},     // 0x4B
	{"JMP", AddressingModeAbsolute, 3, 3},    // 0x4C
	{"EOR", AddressingModeAbsolute, 3, 4},    // 0x4D
	{"LSR", AddressingModeAbsolute, 3, 6},    // 0x4E
	{"???", AddressingModeImplied, 0, 0},     // 0x4F
	{"BVC", AddressingModeRelative, 2, 2},    // 0x50
	{"EOR", AddressingModeIndirectY, 2, 5},   // 0x51
	{"???", AddressingModeImplied, 0, 0},     // 0x52
	{"???", AddressingModeImplied, 0, 0},     // 0x53
	{"???", AddressingModeImplied, 0, 0},     // 0x54
	{"EOR", AddressingModeZeroPageX, 2, 4},   // 0x55
	{"LSR", AddressingModeZeroPageX, 2, 6},   // 0x56
	{"???", AddressingModeImplied, 0, 0},     // 0x57
	{"CLI", AddressingModeImplied, 1, 2},     // 0x58
	{"EOR", AddressingModeAbsoluteY, 3, 4},   // 0x59
	{"???", AddressingModeImplied, 0, 0},     // 0x5A
	{"???", AddressingModeImplied, 0, 0},     // 0x5B
	{"???", AddressingModeImplied, 0, 0},     // 0x5C
	{"EOR", AddressingModeAbsoluteX, 3, 4},   // 0x5D
	{"LSR", AddressingModeAbsoluteX, 3, 7},   // 0x5E
	{"???", AddressingModeImplied, 0, 0},     // 0x5F
	{"RTS", AddressingModeImplied, 1, 6},     // 0x60
	{"ADC", AddressingModeIndirectX, 2, 6},   // 0x61
	{"???", AddressingModeImplied, 0, 0},     // 0x62
	{"???", AddressingModeImplied, 0, 0},     // 0x63
	{"???", AddressingModeImplied, 0, 0},     // 0x64
	{"ADC", AddressingModeZeroPage, 2, 3},    // 0x65
	{"ROR", AddressingModeZeroPage, 2, 5},    // 0x66
	{"???", AddressingModeImplied, 0, 0},     // 0x67
	{"PLA", AddressingModeImplied, 1, 4},     // 0x68
	{"ADC", AddressingModeImmediate, 2, 2},   // 0x69
	{"ROR", AddressingModeAccumulator, 1, 2}, // 0x6A
	{"???", AddressingModeImplied, 0, 0},     // 0x6B
	{"JMP", AddressingModeIndirect, 3, 5},    // 0x6C
	{"ADC", AddressingModeAbsolute, 3, 4},    // 0x6D
	{"ROR", AddressingModeAbsolute, 3, 6},    // 0x6E
	{"???", AddressingModeImplied, 0, 0},     // 0x6F
	{"BVS", AddressingModeRelative, 2, 2},    // 0x70
	{"ADC", AddressingModeIndirectY, 2, 5},   // 0x71
	{"???", AddressingModeImplied, 0, 0},     // 0x72
	{"???", AddressingModeImplied, 0, 0},     // 0x73
	{"???", AddressingModeImplied, 0, 0},     // 0x74
	{"ADC", AddressingModeZeroPageX, 2, 4},   // 0x75
	{"ROR", AddressingModeZeroPageX, 2, 6},   // 0x76
	{"???", AddressingModeImplied, 0, 0},     // 0x77
	{"SEI", AddressingModeImplied, 1, 2},     // 0x78
	{"ADC", AddressingModeAbsoluteY, 3, 4},   // 0x79
	{"???", AddressingModeImplied, 0, 0},     // 0x7A
	{"???", AddressingModeImplied, 0, 0},     // 0x7B
	{"???", AddressingModeImplied, 0, 0},     // 0x7C
	{"ADC", AddressingModeAbsoluteX, 3, 4},   // 0x7D
	{"ROR", AddressingModeAbsoluteX, 3, 7},   // 0x7E
	{"???", AddressingModeImplied, 0, 0},     // 0x7F
	{"???", AddressingModeImplied, 0, 0},     // 0x80
	{"STA", AddressingModeIndirectX, 2, 6},   // 0x81
	{"???", AddressingModeImplied, 0, 0},     // 0x82
	{"???", AddressingModeImplied, 0, 0},     // 0x83
	{"STY", AddressingModeZeroPage, 2, 3},    // 0x84
	{"STA", AddressingModeZeroPage, 2, 3},    // 0x85
	{"STX", AddressingModeZeroPage, 2, 3},    // 0x86
	{"???", AddressingModeImplied, 0, 0},     // 0x87
	{"DEY", AddressingModeImplied, 1, 2},     // 0x88
	{"???", AddressingModeImplied, 0, 0},     // 0x89
	{"TXA", AddressingModeImplied, 1, 2},     // 0x8A
	{"???", AddressingModeImplied, 0, 0},     // 0x8B
	{"STY", AddressingModeAbsolute, 3, 4},    // 0x8C
	{"STA", AddressingModeAbsolute, 3, 4},    // 0x8D
	{"STX", AddressingModeAbsolute, 3, 4},    // 0x8E
	{"???", AddressingModeImplied, 0, 0},     // 0x8F
	{"BCC", AddressingModeRelative, 2, 2},    // 0x90
	{"STA", AddressingModeIndirectY, 2, 6},   // 0x91
	{"???", AddressingModeImplied, 0, 0},     // 0x92
	{"???", AddressingModeImplied, 0, 0},     // 0x93
	{"STY", AddressingModeZeroPageX, 2, 4},   // 0x94
	{"STA", AddressingModeZeroPageX, 2, 4},   // 0x95
	{"STX", AddressingModeZeroPageY, 2, 4},   // 0x96
	{"???", AddressingModeImplied, 0, 0},     // 0x97
	{"TYA", AddressingModeImplied, 1, 2},     // 0x98
	{"STA", AddressingModeAbsoluteY, 3, 5},   // 0x99
	{"TXS", AddressingModeImplied, 1, 2},     // 0x9A
	{"???", AddressingModeImplied, 0, 0},     // 0x9B
	{"???", AddressingModeImplied, 0, 0},     // 0x9C
	{"STA", AddressingModeAbsoluteX, 3, 5},   // 0x9D
	{"???", AddressingModeImplied, 0, 0},     // 0x9E
	{"???", AddressingModeImplied, 0, 0},     // 0x9F
	{"LDY", AddressingModeImmediate, 2, 2},   // 0xA0
	{"LDA", AddressingModeIndirectX, 2, 6},   // 0xA1
	{"LDX", AddressingModeImmediate, 2, 2},   // 0xA2
	{"???", AddressingModeImplied, 0, 0},     // 0xA3
	{"LDY", AddressingModeZeroPage, 2, 3},    // 0xA4
	{"LDA", AddressingModeZeroPage, 2, 3},    // 0xA5
	{"LDX", AddressingModeZeroPage, 2, 3},    // 0xA6
	{"???", AddressingModeImplied, 0, 0},     // 0xA7
	{"TAY", AddressingModeImplied, 1, 2},     // 0xA8
	{"LDA", AddressingModeImmediate, 2, 2},   // 0xA9
	{"TAX", AddressingModeImplied, 1, 2},     // 0xAA
	{"???", AddressingModeImplied, 0, 0},     // 0xAB
	{"LDY", AddressingModeAbsolute, 3, 4},    // 0xAC
	{"LDA", AddressingModeAbsolute, 3, 4},    // 0xAD
	{"LDX", AddressingModeAbsolute, 3, 4},    // 0xAE
	{"???", AddressingModeImplied, 0, 0},     // 0xAF
	{"BCS", AddressingModeRelative, 2, 2},    // 0xB0
	{"LDA", AddressingModeIndirectY, 2, 5},   // 0xB1
	{"???", AddressingModeImplied, 0, 0},     // 0xB2
	{"???", AddressingModeImplied, 0, 0},     // 0xB3
	{"LDY", AddressingModeZeroPageX, 2, 4},   // 0xB4
	{"LDA", AddressingModeZeroPageX, 2, 4},   // 0xB5
	{"LDX", AddressingModeZeroPageY, 2, 4},   // 0xB6
	{"???", AddressingModeImplied, 0, 0},     // 0xB7
	{"CLV", AddressingModeImplied, 1, 2},     // 0xB8
	{"LDA", AddressingModeAbsoluteY, 3, 4},   // 0xB9
	{"TSX", AddressingModeImplied, 1, 2},     // 0xBA
	{"???", AddressingModeImplied, 0, 0},     // 0xBB
	{"LDY", AddressingModeAbsoluteX, 3, 4},   // 0xBC
	{"LDA", AddressingModeAbsoluteX, 3, 4},   // 0xBD
	{"LDX", AddressingModeAbsoluteY, 3, 4},   // 0xBE
	{"???", AddressingModeImplied, 0, 0},     // 0xBF
	{"CPY", AddressingModeImmediate, 2, 2},   // 0xC0
	{"CMP", AddressingModeIndirectX, 2, 6},   // 0xC1
	{"???", AddressingModeImplied, 0, 0},     // 0xC2
	{"???", AddressingModeImplied, 0, 0},     // 0xC3
	{"CPY", AddressingModeZeroPage, 2, 3},    // 0xC4
	{"CMP", AddressingModeZeroPage, 2, 3},    // 0xC5
	{"DEC", AddressingModeZeroPage, 2, 5},    // 0xC6
	{"???", AddressingModeImplied, 0, 0},     // 0xC7
	{"INY", AddressingModeImplied, 1, 2},     // 0xC8
	{"CMP", AddressingModeImmediate, 2, 2},   // 0xC9
	{"DEX", AddressingModeImplied, 1, 2},     // 0xCA
	{"???", AddressingModeImplied, 0, 0},     // 0xCB
	{"CPY", AddressingModeAbsolute, 3, 4},    // 0xCC
	{"CMP", AddressingModeAbsolute, 3, 4},    // 0xCD
	{"DEC", AddressingModeAbsolute, 3, 6},    // 0xCE
	{"???", AddressingModeImplied, 0, 0},     // 0xCF
	{"BNE", AddressingModeRelative, 2, 2},    // 0xD0
	{"CMP", AddressingModeIndirectY, 2, 5},   // 0xD1
	{"???", AddressingModeImplied, 0, 0},     // 0xD2
	{"???", AddressingModeImplied, 0, 0},     // 0xD3
	{"???", AddressingModeImplied, 0, 0},     // 0xD4
	{"CMP", AddressingModeZeroPageX, 2, 4},   // 0xD5
	{"DEC", AddressingModeZeroPageX, 2, 6},   // 0xD6
	{"???", AddressingModeImplied, 0, 0},     // 0xD7
	{"CLD", AddressingModeImplied, 1, 2},     // 0xD8
	{"CMP", AddressingModeAbsoluteY, 3, 4},   // 0xD9
	{"???", AddressingModeImplied, 0, 0},     // 0xDA
	{"???", AddressingModeImplied, 0, 0},     // 0xDB
	{"???", AddressingModeImplied, 0, 0},     // 0xDC
	{"CMP", AddressingModeAbsoluteX, 3, 4},   // 0xDD
	{"DEC", AddressingModeAbsoluteX, 3, 7},   // 0xDE
	{"???", AddressingModeImplied, 0, 0},     // 0xDF
	{"CPX", AddressingModeImmediate, 2, 2},   // 0xE0
	{"SBC", AddressingModeIndirectX, 2, 6},   // 0xE1
	{"???", AddressingModeImplied, 0, 0},     // 0xE2
	{"???", AddressingModeImplied, 0, 0},     // 0xE3
	{"CPX", AddressingModeZeroPage, 2, 3},    // 0xE4
	{"SBC", AddressingModeZeroPage, 2, 3},    // 0xE5
	{"INC", AddressingModeZeroPage, 2, 5},    // 0xE6
	{"???", AddressingModeImplied, 0, 0},     // 0xE7
	{"INX", AddressingModeImplied, 1, 2},     // 0xE8
	{"SBC", AddressingModeImmediate, 2, 2},   // 0xE9
	{"NOP", AddressingModeImplied, 1, 2},     // 0xEA
	{"???", AddressingModeImplied, 0, 0},     // 0xEB
	{"CPX", AddressingModeAbsolute, 3, 4},    // 0xEC
	{"SBC", AddressingModeAbsolute, 3, 4},    // 0xED
	{"INC", AddressingModeAbsolute, 3, 6},    // 0xEE
	{"???", AddressingModeImplied, 0, 0},     // 0xEF
	{"BEQ", AddressingModeRelative, 2, 2},    // 0xF0
	{"SBC", AddressingModeIndirectY, 2, 5},   // 0xF1
	{"???", AddressingModeImplied, 0, 0},     // 0xF2
	{"???", AddressingModeImplied, 0, 0},     // 0xF3
	{"???", AddressingModeImplied, 0, 0},     // 0xF4
	{"SBC", AddressingModeZeroPageX, 2, 4},   // 0xF5
	{"INC", AddressingModeZeroPageX, 2, 6},   // 0xF6
	{"???", AddressingModeImplied, 0, 0},     // 0xF7
	{"SED", AddressingModeImplied, 1, 2},     // 0xF8
	{"SBC", AddressingModeAbsoluteY, 3, 4},   // 0xF9
	{"???", AddressingModeImplied, 0, 0},     // 0xFA
	{"???", AddressingModeImplied, 0, 0},     // 0xFB
	{"???", AddressingModeImplied, 0, 0},     // 0xFC
	{"SBC", AddressingModeAbsoluteX, 3, 4},   // 0xFD
	{"INC", AddressingModeAbsoluteX, 3, 7},   // 0xFE
	{"???", AddressingModeImplied, 0, 0},     // 0xFF
}
